runtime: custom
env: flex
service_account: reddit-scraper-service-account@steady-voltage-236500.iam.gserviceaccount.com
# runtime_config:
#   python_version: 3.7

# entrypoint: streamlit run hydra_main_app.py --server.port $PORT

# automatic_scaling:
#   max_num_instances: 1
